version: '3.9'
services:
    node:
        image: 'node:16.14'
        container_name: svelte-tel-input
        working_dir: /home/node/app
        command: 'sh -c "npm i && npm run prepare && npm run dev -- --host"'
        user: node
        tty: true
        ports:
            # Server
            - '3000:3000'
            # Vite
            - '24678:24678'
        volumes:
            - ./:/home/node/app
